// components/projects/components/ProjectsFilter.vue
<template>
  <div class="border-2 rounded-md">
    <div class="m-1">
      <p class="text-gray-700 -mt-1">Filter Projects:</p>
      <div class="mx-0 relative">
        <input
          v-bind:value="searchText"
          @keydown="onTextChanged"
          :class="'text-xl pl-10 py-1 mb-1 rounded w-full border-2 transition-all ' + (hasText ? 'pr-10' : 'pr-0') "
          type="text"
          placeholder="Filter projects"
        />
        <svg
          class="absolute left-0 top-0 mt-2 ml-2 text-gray-400"
          viewBox="0 0 32 32"
          width="24"
          height="24"
          fill="none"
          stroke="currentcolor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
        >
          <circle cx="14" cy="14" r="12" />
          <path d="M23 23 L30 30" />
        </svg>
        <svg
          :class="'absolute right-0 top-0 mt-3 mr-2 transition-all duration-500 ' + (hasText ? 'text-gray-900' : 'text-transparent')"
          @click="clickedClearSearch"
          viewBox="0 0 32 32"
          width="20"
          height="20"
          fill="none"
          stroke="currentcolor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="4"
        >
          <path d="M2 30 L30 2 M30 30 L2 2" />
        </svg>
      </div>
      <div>
        <div class="flex flex-wrap items-center">
          <span class="text-xs mb-1">Filters: </span>
          <projects-filter-tag
            v-for="tag in selectedTags"
            :key="tag"
            :iconLabel="tag"
            :enabled="tag"
            v-on:clickedItem="clickedTagStr(tag)"
          >
          </projects-filter-tag>
          <projects-filter-tag
            v-for="year in selectedYears"
            :key="year"
            :iconLabel="year"
            :enabled="year"
            v-on:clickedItem="clickedYearStr(year)"
          >
          </projects-filter-tag>
          <projects-filter-tag
            v-for="icon in selectedIcons"
            :key="icon"
            :iconLabel="icon"
            :enabled="icon"
            v-on:clickedItem="clickedIconStr(icon)"
          >
          </projects-filter-tag>
          <projects-filter-tag
            v-if="hasAnyEnabled"
            iconLabel="clear all"
            color="orange"
            :enabled="true"
            v-on:clickedItem="clickedClearAll()"
          >
          </projects-filter-tag>
          <span class="mb-1 ml-1" v-if="!hasAnyEnabled">-</span>
        </div>
        <div class="text-xs">Found: {{ foundCount }} projects</div>
      </div>
    </div>
    <div>
      <filter-container label="Type">
        <div class="flex flex-wrap">
          <projects-filter-tag
            v-for="tag in allTags"
            :key="tag.key"
            :iconLabel="tag.key"
            :count="tag.count"
            :enabled="tag.enabled"
            v-on:clickedItem="clickedTag(tag)"
          >
          </projects-filter-tag>
        </div>
      </filter-container>
      <filter-container label="Year">
        <div class="flex flex-col">
          <projects-filter-item
            v-for="year in allYears"
            :key="year.key"
            iconName="plus"
            :iconLabel="year.key"
            :enabled="year.enabled"
            v-on:clickedItem="clickedYear(year)"
          >
          </projects-filter-item>
        </div>
      </filter-container>
      <filter-container label="Tech">
        <div class="flex flex-col">
          <projects-filter-item
            v-for="icon in allIcons"
            :key="icon.key"
            :iconName="icon.key"
            :iconLabel="icon.key"
            :enabled="icon.enabled"
            v-on:clickedItem="clickedIcon(icon)"
          >
          </projects-filter-item>
        </div>
      </filter-container>
    </div>
  </div>
</template>

<script>
import ProjectsFilterItem from "./ProjectsFilterItem";
import ProjectsFilterTag from "./ProjectsFilterTag";
import FilterContainer from "./FilterContainer";

export default {
  props: ["projectsall", "foundCount"],
  components: {
    FilterContainer,
    ProjectsFilterItem,
    ProjectsFilterTag,
  },
  data() {
    return {
      selectedYears: [],
      selectedTags: [],
      selectedIcons: [],
      allYears: [],
      allTags: [],
      allIcons: [],
      searchText: "",
    };
  },
  watch: {
    projectsall: {
      immediate: true,
      handler(newVal, oldVal) {
        this.allYears = this.MakeAllYears();
        this.allTags = this.MakeAllTags();
        this.allIcons = this.MakeAllIcons();
      },
    },
  },
  computed: {
    projectsAllSafe() {
      const all = this.projectsall;
      if (!all || !all.length) {
        return [];
      }
      return all;
    },
    hasAnyEnabled() {
      return (
        !!this.selectedYears.length ||
        !!this.selectedTags.length ||
        !!this.selectedIcons.length
      );
    },
    hasText() {
      return !!this.searchText;
    }
  },
  methods: {
    MakeAllYears() {
      const years = this.projectsAllSafe.map((val) => val.year);
      const unique = Array.from(new Set(years));
      unique.sort((a, b) => b - a);
      const uniqueObj = ConvertToEnabledObjs(unique);
      return uniqueObj;
    },
    MakeAllTags() {
      const tags = this.projectsAllSafe
        .map((val) => val.tags)
        .reduce((acc, cur) => acc.concat(cur), []);
      const tagsMap = tags.reduce((acc, cur) => {
        if (!Number.isFinite(acc[cur])) {
          acc[cur] = 0;
        }
        acc[cur]++;
        return acc;
      }, {});
      const tagsArr = Object.entries(tagsMap).map(([tag, count]) => {
        return { key: tag, count };
      });
      tagsArr.sort((a, b) => b.count - a.count);
      const uniqueObj = ConvertToEnabledObjs2(tagsArr);
      console.log({ tagsArr, uniqueObj });
      return uniqueObj;
    },
    MakeAllIcons() {
      const icons = this.projectsAllSafe
        .map((val) => val.icons)
        .reduce((acc, cur) => acc.concat(cur), []);
      const unique = Array.from(new Set(icons));
      unique.sort();
      const uniqueObj = ConvertToEnabledObjs(unique);
      return uniqueObj;
    },
    toggle(inputArr, inputVal) {
      const index = inputArr.findIndex((a) => a === inputVal.key);
      if (index >= 0) {
        inputVal.enabled = false;
        inputArr.splice(index, 1);
      } else {
        inputVal.enabled = true;
        inputArr.push(inputVal.key);
      }
    },
    clickedClearSearch() {
      this.searchText = '';
      this.emitChanged();
    },
    clickedIconStr(iconStr) {
      const icon = this.allIcons.find((i) => i.key === iconStr);
      this.toggleIcon(icon);
    },
    clickedYearStr(yearStr) {
      const year = this.allYears.find((i) => i.key === yearStr);
      this.toggleYear(year);
    },
    clickedTagStr(tagStr) {
      const tag = this.allTags.find((i) => i.key === tagStr);
      this.toggleTag(tag);
    },
    clickedIcon(icon) {
      this.toggleIcon(icon);
    },
    clickedYear(year) {
      this.toggleYear(year);
    },
    clickedTag(tag) {
      this.toggleTag(tag);
    },
    toggleIcon(icon) {
      this.toggle(this.selectedIcons, icon);
      this.selectedIcons = this.selectedIcons;
      this.emitChanged();
    },
    toggleYear(year) {
      this.toggle(this.selectedYears, year);
      this.selectedYears = this.selectedYears;
      this.emitChanged();
    },
    toggleTag(tag) {
      this.toggle(this.selectedTags, tag);
      this.selectedTags = this.selectedTags;
      this.emitChanged();
    },
    clickedClearAll() {
      this.allYears.map((a) => (a.enabled = false));
      this.allTags.map((a) => (a.enabled = false));
      this.allIcons.map((a) => (a.enabled = false));
      this.selectedYears = [];
      this.selectedTags = [];
      this.selectedIcons = [];
      this.emitChanged();
    },
    onTextChanged(e) {
      setTimeout(() => {
        this.searchText = e.target.value;
        this.emitChanged();
      });
    },
    emitChanged() {
      const filterChangedEvent = {
        years: this.selectedYears,
        tags: this.selectedTags,
        icons: this.selectedIcons,
        searchText: this.searchText,
      };
      // console.log("emitChanged", { filterChangedEvent });
      this.$emit("filterChanged", filterChangedEvent);
    },
  },
};

function ConvertToEnabledObjs(unique) {
  return unique.map((u) => {
    return {
      key: u,
      enabled: false,
    };
  });
}

function ConvertToEnabledObjs2(unique) {
  return unique.map((u) => {
    return {
      ...u,
      enabled: false,
    };
  });
}
</script>

// src/components/projects/ProjectsFilter.tsx
import classNames from "classnames";
import { Icon, IconName } from "components/icons/icons";
import { OrderArr } from "components/utils/OrderArr";
import React from "react";
import { FilterContainer } from "./components/FilterContainer";
import { ProjectsFilterItem } from "./components/ProjectsFilterItem";
import { ProjectsFilterTag } from "./components/ProjectsFilterTag";
import { Project } from "./projects-service";

export type ProjectFilterValue = {
  years?: number[];
  tags?: string[];
  icons?: string[];
  searchText?: string;
};

export function ProjectsFilter(props: {
  projectsAll: Project[];
  foundCount: number;
  value: ProjectFilterValue,
  onFilterChanged: (value: ProjectFilterValue) => void;
}) {
  const {
    years: allYears,
    tags: allTags,
    icons: allIcons,
  } = React.useMemo(() => {
    const projectsSafe = props.projectsAll || [];
    return MakeAll(projectsSafe);
  }, [props.projectsAll]);

  const {
    years: selectedYears,
    tags: selectedTags,
    icons: selectedIcons,
    searchText,
  } = props.value;

  const hasAnyEnabled = selectedYears?.length || selectedTags?.length || selectedIcons?.length;

  const onTextChanged = (text: string) => props.onFilterChanged({
    searchText: text,
  });
  const clickedClearSearch = () => props.onFilterChanged({
    searchText: '',
  });
  const clickedIconStr = (icon: string) => props.onFilterChanged({ 
    icons: toggleInArray(selectedIcons, icon)
  });
  const clickedYearStr = (year: string) => props.onFilterChanged({ 
    years: toggleInArray(selectedYears, parseInt(year))
  });
  const clickedTagStr = (tag: string) => props.onFilterChanged({ 
    tags: toggleInArray(selectedTags, tag)
  });

  const selectedYearsStr = selectedYears.map(y => y+'');

  const clickedClearAll = () => {
    props.onFilterChanged({
      years: [],
      tags: [],
      icons: [],
    })
  };

  return (
    <div className="border-2 rounded-md">
      <div className="m-1">
        <p className="text-gray-700 -mt-1">Filter Projects:</p>
        <SearchField
          searchText={searchText}
          clickedClearSearch={clickedClearSearch}
          onTextChanged={onTextChanged}
        />
        <div>
          <div className="flex flex-wrap items-center">
            <span className="text-xs mb-1">Filters:</span>
            <ProjectFiltersSelectedTags items={allTags} selected={selectedTags} clickedItem={clickedTagStr} />
            <ProjectFiltersSelectedTags items={allYears} selected={selectedYearsStr} clickedItem={clickedYearStr} />
            <ProjectFiltersSelectedTags items={allIcons} selected={selectedIcons} clickedItem={clickedIconStr} />
            {hasAnyEnabled && (
              <ProjectsFilterTag
                iconLabel="clear all"
                color="orange"
                enabled={true}
                clickedItem={clickedClearAll}
              />
            )}
            <span className="mb-1 ml-1" v-if="!hasAnyEnabled">-</span>
          </div>
          <div className="text-xs">Found: {props.foundCount} projects</div>
        </div>
      </div>
      <div>
        <FilterContainer label="Tags">
          <div className="flex flex-wrap">
            <ProjectsFilterTagList items={allTags} clickedItem={clickedTagStr} selected={selectedTags} />
          </div>
        </FilterContainer>
        <FilterContainer label="Year">
          <div className="flex flex-col">
            <ProjectsFilterItemList items={allYears} clickedItem={clickedYearStr} selected={selectedYearsStr} />
          </div>
        </FilterContainer>
        <FilterContainer label="Tech">
          <div className="flex flex-col">
            <ProjectsFilterItemList items={allIcons} clickedItem={clickedIconStr} selected={selectedIcons} />
          </div>
        </FilterContainer>
      </div>
    </div>
  );
}

function ProjectsFilterItemList(
  props: { items: FilterItem[]; selected: string[]; clickedItem: (key: string) => void },
) {
  return (
    <>
      {props.items?.map(item => (
        <ProjectsFilterItem
          key={item.label}
          iconName={item.iconName}
          iconLabel={item.label}
          enabled={props.selected?.includes(item.key)}
          clickedItem={() => props.clickedItem(item.key)}
        />
      ))}
    </>
  );
}

function ProjectsFilterTagList(props: { items: FilterItem[]; selected: string[]; clickedItem: (key: string) => void }) {
  return (
    <>
      {props.items?.map(item => (
        <ProjectsFilterTag
          key={item.label}
          iconLabel={item.label}
          enabled={props.selected?.includes(item.key)}
          clickedItem={() => props.clickedItem(item.key)}
          count={str(item.count)}
          color={""}
        />
      ))}
    </>
  );
}

function ProjectFiltersSelectedTags(
  props: { items: FilterItem[]; selected: string[]; clickedItem: (key: string) => void },
) {
  return (
    <>
      {props.items?.map(item =>
        props.selected?.includes(item.key) && (
          <ProjectsFilterTag
            key={item.label}
            iconLabel={item.label}
            enabled={true}
            clickedItem={() => props.clickedItem(item.key)}
            count={str(item.count)}
            color={""}
          />
        )
      )}
    </>
  );
}

function SearchField(
  props: { searchText: string; onTextChanged: (text: string) => void; clickedClearSearch: () => void },
) {
  const hasText = !!props.searchText;
  return (
    <div className="mx-0 relative">
      <input
        value={props.searchText}
        onChange={e => props.onTextChanged(e.currentTarget.value)}
        className={classNames(
          hasText ? "pr-10" : "pr-0",
          "text-xl pl-10 py-1 mb-1 rounded w-full border-2 transition-all",
        )}
        type="text"
        placeholder="Filter projects"
      />
      <Icon
        width={24}
        className="absolute left-0 top-0 mt-2 ml-2 text-gray-400"
        iconName="search"
      />
      <Icon
        width={20}
        onClick={props.clickedClearSearch}
        className={classNames(
          hasText ? "text-gray-900 cursor-pointer" : "text-transparent",
          "absolute right-0 top-0 mt-3 mr-2 transition-all duration-500",
        )}
        iconName="closex"
      />
    </div>
  );
}

type FilterItem = {
  key: string;
  label: string;
  count?: number;
  iconName?: IconName;
};

function MakeAll(projectsAll: Project[]) {
  const yearsUnique = new Set<string>();
  const tagsUniqueCount: Record<string, number> = {};
  const iconsUnique = new Set<IconName>();
  projectsAll.map((project) => {
    yearsUnique.add(str(project.year));
    project.tags?.map(tag => {
      if (!tagsUniqueCount[tag]) tagsUniqueCount[tag] = 0;
      tagsUniqueCount[tag]++;
    });
    project.icons?.map(icon => iconsUnique.add(icon));
  });
  const yearsStrings = Array.from(yearsUnique).sort();
  const iconsString = Array.from(iconsUnique).sort();
  const tagCounts = Object.entries(tagsUniqueCount).map(([key, count]) => {
    return { key, count } as KeyCount;
  });
  OrderArr(tagCounts, "count", false);
  // Years
  function YearToFilter(year: string): FilterItem {
    return {
      key: str(year),
      label: str(year),
    };
  }
  const years = yearsStrings.map(YearToFilter);
  // Tags
  function TagToFilter(tag: KeyCount): FilterItem {
    return {
      key: str(tag.key),
      label: str(tag.key),
      count: tag.count,
    };
  }
  const tags = tagCounts.map(TagToFilter);
  // Icons
  function IconToFilter(iconName: IconName): FilterItem {
    return {
      key: str(iconName),
      label: str(iconName),
      iconName,
    };
  }
  const icons = iconsString.map(IconToFilter);

  return {
    years,
    tags,
    icons,
  };
}

type KeyCount = {
  key: IconName;
  count: number;
};

function toggleInArray<T>(arr: T[], value: T) {
  const arrCopy = [...arr];
  if (arrCopy.includes(value)) {
    arrCopy.splice(arrCopy.findIndex(v => v === value), 1);
  } else {
    arrCopy.push(value);
  }
  return arrCopy;
}

function str(input: number | string | undefined): string {
  return (input || "") + "";
}
