// components/projects/components/ProjectsFilterItem.vue
<template>
  <div class="w-full">
    <label
      :class="enabled ? 'bg-blue-400' : ''"
      class="cursor-pointer hover:bg-gray-400 flex items-center"
      v-on:click="clickedIcon()"
    >
      <Icon width="28" class="p-1" v-bind:iconName="iconName"></Icon>
      <span class="w-full">{{ iconLabel }}</span>
      <span>
        <svg
          v-if="enabled"
          class="mr-1"
          id="i-close"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 32 32"
          width="16"
          height="16"
          fill="none"
          stroke="currentcolor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="4"
        >
          <path d="M2 30 L30 2 M30 30 L2 2" />
        </svg>
      </span>
    </label>
  </div>
</template>

<script>
import Icon from "~/components/Icon";

export default {
  props: ["enabled", "iconName", "iconLabel"],
  components: {
    Icon
  },
  methods: {
    clickedIcon() {
      this.$emit("clickedItem", this.iconName);
    }
  }
};
</script>

// components/projects/components/ProjectsFilterItem.tsx
import classNames from "classnames";
import { Icon, IconName } from "components/icons/icons";

export function ProjectsFilterItem(props: {
  enabled: boolean,
  iconName: IconName,
  iconLabel: string,
  clickedItem: () => void,
}) {
  return <div className="w-full">
    <label
      className={classNames(props.enabled && 'bg-blue-400', "cursor-pointer hover:bg-gray-400 flex items-center")}
      onClick={props.clickedItem}
    >
      <Icon width={24} className="mx-1 py-1" iconName={props.iconName} />
      <span className="w-full">{props.iconLabel}</span>
      <span>
        {props.enabled && <Icon iconName="uparrow"/>}
      </span>
    </label>
  </div>;
}
