// components/Header.tsx
import Link from "next/link";
import React from "react";

function HeadLink(props: { href: string, children: React.ReactNode }) {
  return <Link href={props.href}><a className="mr-3">{props.children}</a></Link>
}

// TODO current link higlighted 
export function Header() {
  return <div>
    <div className="text-right text-blue-800 text md:text-2xl mt-4">
      <HeadLink href="/">Home</HeadLink>
      <HeadLink href="/about">About</HeadLink>
      <HeadLink href="/projects">Projects</HeadLink>
      <HeadLink href="/contact">Contact</HeadLink>
      <a className="mr-3" href="/3d/">3D</a>
    </div>
    <a className="fixed border-8 border-red-400 opacity-50 bottom-0 left-0 w-6 h-6 m-2 rounded-full" href="/eat-the-donut.html"></a>
  </div>;
}

// components/Header.vue
<template>
  <div>
    <div class="text-right text-blue-800 text-xl md:text-2xl mt-4">
      <nuxt-link class="mr-3" to="/">Home</nuxt-link>
      <nuxt-link class="mr-3" to="/about">About</nuxt-link>
      <nuxt-link class="mr-3" to="/projects">Projects</nuxt-link>
      <nuxt-link class="mr-3" to="/contact">Contact</nuxt-link>
    </div>
    <a class="fixed border-8 border-red-400 opacity-50 bottom-0 left-0 w-6 h-6 m-2 rounded-full" href="/eat-the-donut.html"></a>
  </div>
</template>

<script></script>

<style lang="scss" scoped>
.nuxt-link-exact-active {
  border-bottom: 2px solid #2c5282;
}
</style>
