// src/components/RainbowText.vue
<template>
  <div :class="{ large }">
    <span v-for="(letter, index) in text" :key="index">
      <rainbow-letter v-if="letter !== ' '" :letter="letter"
        v-bind:style="{ color: getColor(index) }"
      ></rainbow-letter>
      <br v-else>
    </span>
  </div>
</template>

<script>
  import RainbowLetter from './RainbowLetter'
  import * as interpolate from 'color-interpolate'

  export default {
    props: ['text', 'large'],
    components: {
      'rainbow-letter': RainbowLetter
    },
    methods: {
      getColor (index) {
        const colors = [
        '#800000',
        '#A21051',
        '#9D4B9E',
        '#6B7DD8',
        '#00A8F1',
        '#00CBEB',
        ].reverse();
        let colormap = interpolate(colors);
        const min = 0;
        const max = this.text.length;
        const val = (max - index) / (max - min)
        return colormap(val);
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import url('https://fonts.googleapis.com/css?family=Lato:400,800');
    
  div > span > span {
    font-size: 80px;
    letter-spacing: -10px;

    @media (max-width: 500px) {
      font-size: 80px;
    }
  }

  .large > span > span {
    font-size: 200px;
    line-height: 60%;

    @media (max-width: 1050px) {
      font-size: 170px;
    }

    @media (max-width: 800px) {
      font-size: 120px;
    }

    @media (max-width: 600px) {
      font-size: 70px;
    }
    @media (max-width: 350px) {
      font-size: 55px;
    }
  }

</style>

// components/RainbowText.tsx
import interpolate from 'color-interpolate'
import React from "react";
import styles from './RainbowText.module.css';
import classNames from "classnames";

export function RainbowText(props: {
  text: string,
  large?: boolean,
}) {
  return <div className={classNames('uppercase', 
    props.large
    ? 'text-6xl sm:text-8xl'
    : 'text-6xl'
  )}>
    {Array.from(props.text).map((letter, index) =>
    (<span key={index}>
      {letter !== ' ' && <RainbowLetter
        letter={letter}
        color={getColor(index, props.text.length)}
      ></RainbowLetter>}
    </span>))}
  </div>;
}

function getColor(index: number, max: number): string {
  const colors = [
    '#800000',
    '#A21051',
    '#9D4B9E',
    '#6B7DD8',
    '#00A8F1',
    '#00CBEB',
  ].reverse();
  let colormap = interpolate(colors);
  const min = 0;
  const val = (max - index) / (max - min)
  return colormap(val);
}

function RainbowLetter(props: {
  letter: string,
  color: string,
}) {
  const [hovered, setHovered] = React.useState(false);

  React.useEffect(() => {
    let mounted = true;
    if (!hovered) return;
    setTimeout(() => mounted && setHovered(false), 3200);
    return () => { mounted = false; }
  }, [hovered]);

  const onHover = () => {
    if (hovered) return;
    setHovered(true);
  }

  return <span className={classNames(styles.letter, {
    [styles.hovered]: hovered,
  })}
    style={{ color: props.color }}
    onMouseOver={onHover}>
    {props.letter}
  </span>
}
