// pages/about.vue
<template>
  <div>
    <rainbow-text text="About"></rainbow-text>
    <div class="flex flex-col md:flex-row">
      <img class="w-64 h-64 rounded-full border-8 border-red-900 p-1 mr-6 shadow-lg shadow-2xl" src="/images/pic.jpg" alt="selfie!" />
      <div class="w-full">
        <h2 class="text-2xl">History</h2>
        <p class="mb-2">Growing up in Adelaide, South Australia. Ben began his life as a normal child, with all the prospects of becoming a contributing member of society. He's trying his best and will continue to do so.</p>
        <h2 class="text-2xl">Now</h2>
        <p class="mb-2">He intends to be a successful web developer, making the internet a better place for all those who use it.</p>
        <h2 class="text-2xl">Development</h2>
        <p class="mb-2">Github contributions (<a href="https://github.com/benwinding">source</a>)</p>
        <img width="100%" style="margin-bottom: 10px;" src="https://ghchart.rshah.org/benwinding" alt="2016rshah's Github chart" />
        <h2 class="text-2xl">Writing</h2>
        <transition-group name="list" tag="p">
          <div class="mb-1" v-for="(blog) in blogPosts" :key="blog.title">
            <a class="flex flex-col" :href="blog.link">
              <p class="-mb-2 text-gray-600 text-xs">{{ blog.date }}</p>
              <p class="m-0 title">{{ blog.title }}</p>
            </a>
          </div>
        </transition-group>
      </div>
    </div>
  </div>
</template>

<script>
import RainbowText from "~/components/RainbowText";
import axios from "axios";

function getBlogPosts() {
  return axios
    .get("https://blog.benwinding.com/feed.json", {
      json: true,
      crossdomain: true
    })
    .then(function(response) {
      console.log(response);
      return response.data;
    });
}

export default {
  head: {
    meta: [
      { property: "og:image", content: "https://i.imgur.com/orqq5jB.jpg" },
      { property: "og:title", content: "About - Ben Winding" },
      {
        property: "og:description",
        content: "A web developer from Adelaide, South Australia."
      }
    ],
    title: "About"
  },
  components: {
    "rainbow-text": RainbowText
  },
  data() {
    return {
      blogPosts: []
    };
  },
  mounted() {
    this.$nextTick(() => {
      getBlogPosts()
        .then(data => {
          let posts = data.slice(0, 6).map(item => {
            return {
              title: item.title,
              date: new Date(item.date).toDateString(),
              link: "https://blog.benwinding.com/" + item.path
            };
          });
          posts.push({
            link: "https://blog.benwinding.com/",
            title: ". . . . . . . ."
          });
          let delayMs = 0;
          for (let post of posts) {
            delayMs += 300;
            setTimeout(() => {
              this.blogPosts.push(post);
            }, delayMs);
          }
        })
        .catch(function(error) {
          console.log(error);
        });
    });
    // GitHubActivity.feed({
    //   username: "benwinding",
    //   selector: "#feed",
    //   limit: 20 // optional
    // });
  }
};
</script>

<style lang="scss" scoped>
.list-enter-active,
.list-leave-active {
  transition: all 1s;
}
.list-enter, .list-leave-to /* .list-leave-active below version 2.1.8 */ {
  opacity: 0;
  transform: translateY(30px);
}
</style>

// pages/about/index.tsx
import { Loading } from "components/Loading";
import { RainbowText } from "components/RainbowText";
import React from "react";
import { TransitionGroup, CSSTransition } from "react-transition-group";
import axios from "axios";
import { DefaultLayout } from "layouts/default";
import styles from "./index.module.css";
import classNames from "classnames";

type BlogPost = {
  title: string,
  link: string,
  path: string,
  date: string,
}

async function getBlogPosts() {
  const response = await axios
    .get("https://blog.benwinding.com/feed.json", {
      responseType: 'json',
    });
  console.log(response);
  return response.data as BlogPost[];
}

const TRANSITION_DELAY = 300;

export default function Page() {
  const [blogPosts, setBlogPosts] = React.useState([]);

  React.useEffect(() => {
    let mounted = true;
    getBlogPosts().then(data => {
      let posts = data.slice(0, 6).map(item => {
        return {
          title: item.title,
          date: new Date(item.date).toDateString(),
          link: "https://blog.benwinding.com/" + item.path
        };
      });
      console.log(posts)
      let delayMs = 0;
      for (let i = 0; i < posts.length; i++) {
        delayMs += TRANSITION_DELAY;
        setTimeout(() => {
          mounted && setBlogPosts(posts.slice(0, i));
        }, delayMs);
        if (!mounted) return;
      }
    })
    return () => {
      mounted = false;
    }
  }, []);

  return <DefaultLayout>
    <RainbowText text="About"></RainbowText>
    <div className="flex flex-col md:flex-row">
      <img
        className="w-64 h-64 rounded-full border-8 border-red-900 p-1 mr-6 shadow-lg shadow-2xl"
        src="/images/pic.jpg"
        alt="selfie!"
      />
      <div className="w-full">
        <h2 className="text-2xl">History</h2>
        <p className="mb-2">
          Growing up in Adelaide, South Australia. Ben began his life as a
          normal child, with all the prospects of becoming a contributing member
          of society. He's trying his best and will continue to do so.
        </p>
        <h2 className="text-2xl">Now</h2>
        <p className="mb-2">
          He intends to be a successful web developer, making the internet a
          better place for all those who use it. <a className="link" href="/projects/">See projects!</a>
        </p>
        <h2 className="text-2xl">Development</h2>
        <p className="mb-2">
          Github contributions (
          <a href="https://github.com/benwinding">
            source
          </a>)
        </p>
        <GithubContributions />
        <h2 className="text-2xl">Writing</h2>
        {!blogPosts?.length && <Loading text="Loading Posts..."></Loading>}
        <TransitionGroup>
          {blogPosts.map((blog) =>
            <CSSTransition
              key={blog.title}
              timeout={1000}
              classNames={{
                enterActive: styles.MyClassEnterActive,
                enterDone: styles.MyClassEnterDone,
              }}
            >
              <div className="mb-1" key={blog.title}>
                <a className="flex flex-col" href={blog.link}>
                  <p className="-mb-2 text-gray-600 text-xs">{blog.date}</p>
                  <p className="m-0 title">{blog.title}</p>
                </a>
              </div>
            </CSSTransition>
          )}
        </TransitionGroup>
      </div>
    </div>
  </DefaultLayout>;
}

function GithubContributions() {
  const [loaded, setLoaded] = React.useState(false);
  const image = React.useRef<HTMLImageElement>()

  React.useEffect(() => {
    if (image.current?.complete) setLoaded(true)
  }, []);

  return <>
    {!loaded && <Loading
      text="Loading Contributions..."
    ></Loading>}
    <a href="https://github.com/benwinding">
      <img
        ref={image}
        onLoad={() => setLoaded(true)}
        width="100%"
        className="mb-3 overflow-hidden"
        style={{ height: !loaded ? '0px' : 'unset' }}
        src="https://ghchart.rshah.org/benwinding"
        alt="Ben Winding's Github Contributions"
      />
    </a>
  </>
}
