// src/views/About.vue
<template>
  <div>
    <rainbow-text text="ABOUT"></rainbow-text>
    <div class="bio-pic">
      <img class="circular" src="../assets/pic.jpg" alt="selfie!">
      <div class="about-box"><h2>History</h2>
      <p>Growing up in Adelaide, South Australia. Ben began his life as a normal child, with all the prospects of becoming a contributing member of society. He's trying his best and will continue to do so.</p>
      <h2>Now</h2>
      <p>He intends to be a successful web developer, making the internet a better place for all those who use it.</p>
      </div>
    </div>
  </div>
</template>

<script>
import RainbowText from "@/components/RainbowText"

export default {
  components: {
    'rainbow-text': RainbowText,
  } 
}
</script>

<style lang="scss" scoped>
p {
  font-size: 18px;
}

.bio-pic {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  align-items: center;

  @media (max-width: 800px) {
    flex-direction: column;
  }
}

.circular {
  -ms-flex-item-align: center;
  margin-right: 40px;
  width: 300px;
  height: 300px;
  border-radius: 50%;
  float: left;
  margin-bottom: 20px;
  border: 15px solid #800000bb;
  
  @media (max-width: 800px) {
    margin-right: 0px;
  }
}

.circular:hover {
  -ms-transform: rotate(360deg); 
  -webkit-transform: rotate(360deg);
  transform: rotate(360deg);
  -webkit-transition-duration: 3s;
  -moz-transition-duration: 3s;
  transition-duration: 3s;
}
</style>

// pages/about.tsx
import { Loading } from "components/Loading";
import { RainbowText } from "components/RainbowText";
import React from "react";
import { TransitionGroup, CSSTransition } from "react-transition-group";
import axios from "axios";
import { DefaultLayout } from "layouts/default";

type BlogPost = {
  title: string,
  link: string,
  path: string,
  date: string,
}

async function getBlogPosts() {
  const response = await axios
    .get("https://blog.benwinding.com/feed.json", {
      responseType: 'json',
    });
  console.log(response);
  return response.data as BlogPost[];
}

const TRANSITION_DELAY = 300;

export default function Page() {
  const [blogPosts, setBlogPosts] = React.useState([]);

  React.useEffect(() => {
    let mounted = true;
    getBlogPosts().then(data => {
      let posts = data.slice(0, 6).map(item => {
        return {
          title: item.title,
          date: new Date(item.date).toDateString(),
          link: "https://blog.benwinding.com/" + item.path
        };
      });
      console.log(posts)
      let delayMs = 0;
      for (let i = 0; i < posts.length; i++) {
        delayMs += TRANSITION_DELAY;
        setTimeout(() => {
          mounted && setBlogPosts(posts.slice(0, i));
        }, delayMs);
        if (!mounted) return;
      }
    })
    return () => {
      mounted = false;
    }
  }, []);

  return <DefaultLayout>
    <RainbowText text="About"></RainbowText>
    <div className="flex flex-col md:flex-row">
      <img
        className="w-64 h-64 rounded-full border-8 border-red-900 p-1 mr-6 shadow-lg shadow-2xl"
        src="/images/pic.jpg"
        alt="selfie!"
      />
      <div className="w-full">
        <h2 className="text-2xl">History</h2>
        <p className="mb-2">
          Growing up in Adelaide, South Australia. Ben began his life as a
          normal child, with all the prospects of becoming a contributing member
          of society. He's trying his best and will continue to do so.
        </p>
        <h2 className="text-2xl">Now</h2>
        <p className="mb-2">
          He intends to be a successful web developer, making the internet a
          better place for all those who use it.
        </p>
        <h2 className="text-2xl">Development</h2>
        <p className="mb-2">
          Github contributions (
          <a href="https://github.com/benwinding">
            source
          </a>)
        </p>
        <GithubContributions />
        <h2 className="text-2xl">Writing</h2>
        {!blogPosts?.length && <Loading text="Loading Posts..."></Loading>}
        <TransitionGroup>
          {blogPosts.map((blog) =>
            <CSSTransition
              key={blog.title}
              timeout={TRANSITION_DELAY}
              classNames="item"
            >
              <div className="mb-1" key={blog.title}>
                <a className="flex flex-col" href={blog.link}>
                  <p className="-mb-2 text-gray-600 text-xs">{blog.date}</p>
                  <p className="m-0 title">{blog.title}</p>
                </a>
              </div>
            </CSSTransition>
          )}
        </TransitionGroup>
      </div>
    </div>
  </DefaultLayout>;
}

function GithubContributions() {
  const [loaded, setLoaded] = React.useState(false);
  const image = React.useRef<HTMLImageElement>()

  React.useEffect(() => {
    if (image.current?.complete) setLoaded(true)
  }, []);

  return <>
    {!loaded && <Loading
      text="Loading Contributions..."
    ></Loading>}
    <a href="https://github.com/benwinding">
      <img
        ref={image}
        onLoad={() => setLoaded(true)}
        width="100%"
        className="mb-3 overflow-hidden"
        style={{ height: !loaded ? '0px' : 'unset' }}
        src="https://ghchart.rshah.org/benwinding"
        alt="Ben Winding's Github Contributions"
      />
    </a>
  </>
}
