// pages/index.vue
<template>
  <div>
    <div class="v-center">
      <div class="zoom-me">
        <rainbow-text text="Ben Winding" :large="true"></rainbow-text>
        <h2 class="intro">
          Complex solutions create complex bugs...
        </h2>
      </div>
    </div>
  </div>
</template>

<script>
import RainbowText from "~/components/RainbowText";

export default {
  head: {
    meta: [
      { property: "og:image", content: "https://i.imgur.com/orqq5jB.jpg" },
      { property: "og:title", content: "Home - Ben Winding" },
      {
        property: "og:description",
        content: "A web developer from Adelaide, South Australia.",
      },
    ],
    title: "Home",
  },
  components: {
    "rainbow-text": RainbowText,
  },
};
</script>

<style lang="scss">
.intro {
  margin-bottom: -10px;
  font-size: 2em;
  font-weight: normal;
  color: #4a4a4a;

  @media (max-width: 650px) {
    font-size: 1.5em;
  }

  span {
    display: inline-grid;
  }
}

.intro a {
  text-decoration: none;
  color: #2196f3;
}

.v-center {
  padding-top: 21vh;
}

.zoom-me {
  transition: 1s;
  animation: zoomin 1.9s;
}

@keyframes zoomin {
  0% {
    transform: scale(0.8);
    opacity: 0;
  }
  100% {
    transform: scale(1);
    opacity: 1;
  }
}
</style>

// pages/index.tsx
import { RainbowText } from "components/RainbowText";
import Head from "next/head";
import { DefaultLayout } from "~/layouts/default";

export default function Page() {
  return <DefaultLayout>
    <Head>
      <title>Home</title>
      <meta property="og:image" content="https://i.imgur.com/orqq5jB.jpg"></meta>
      <meta property="og:title" content="Home - Ben Winding"></meta>
      <meta property="og:description" content="A web developer from Adelaide, South Australia."></meta>
    </Head>
    <div className="absolute left-0" style={{
      top: '50%',
      transform: 'translateY(-50%)',
    }}>
      <div className="relative">
        <RainbowText text="Ben Winding" large></RainbowText>
        <p className="ml-2">Complex solutions create complex bugs...</p>
      </div>
    </div>
  </DefaultLayout>;
}
